
SET SQL DIALECT 3; 

/* CREATE DATABASE 'D:\INSTALL\OJ\Others\Tog shabbodasi+\base\BASE.fdb' PAGE_SIZE 4096 DEFAULT CHARACTER SET UTF8 */


/*  Generators or sequences */
CREATE GENERATOR GEN_TBLUDS_ID;
CREATE GENERATOR GEN_TEDIZM_ID;
CREATE GENERATOR GEN_TIZOX_ID;
CREATE GENERATOR GEN_TMPPRN_ID;
CREATE GENERATOR GEN_TNAKL_ID;
CREATE GENERATOR GEN_TORDERS_ID;
CREATE GENERATOR GEN_TORDERS_IDALL;
CREATE GENERATOR GEN_TOTDELS_ID;
CREATE GENERATOR GEN_TOTKAZ_ID;
CREATE GENERATOR GEN_TTMOVE_ID;
CREATE GENERATOR GEN_TTOVAR_ID;
CREATE GENERATOR GEN_TUSERS_ID;


/* Table: TBLUDS, Owner: SYSDBA */
CREATE TABLE TBLUDS (BLUDID INTEGER NOT NULL,
        OTDELID INTEGER DEFAULT 1 NOT NULL,
        NAIM VARCHAR(50) DEFAULT 'NewBlud' NOT NULL,
        PRICE INTEGER DEFAULT 1 NOT NULL,
        AVAIL INTEGER DEFAULT 0 NOT NULL,
        KOD INTEGER DEFAULT '1' NOT NULL,
        ISSALE SMALLINT DEFAULT 1 NOT NULL,
        ISSLAVEOF INTEGER DEFAULT 0 NOT NULL,
        ISTOVAROF INTEGER DEFAULT 0 NOT NULL,
        TBKOLVO DOUBLE PRECISION DEFAULT 0 NOT NULL,
        VIHOD DOUBLE PRECISION DEFAULT 1 NOT NULL,
        SEBEST FLOAT DEFAULT 0 NOT NULL,
        ISACTIVE INTEGER DEFAULT 0 NOT NULL,
        OSTATKA INTEGER DEFAULT 0 NOT NULL,
        PRR INTEGER DEFAULT 0 NOT NULL,
        NAVBAT INTEGER DEFAULT 999 NOT NULL,
        TYPE INTEGER DEFAULT 0 NOT NULL,
        TID INTEGER DEFAULT 0 NOT NULL,
CONSTRAINT PK_TBLUDS PRIMARY KEY (BLUDID));

/* Table: TEDIZM, Owner: SYSDBA */
CREATE TABLE TEDIZM (IDEDI INTEGER NOT NULL,
        NAIM VARCHAR(15),
        TIP SMALLINT,
        KOEFF INTEGER,
CONSTRAINT PK_TEDIZM PRIMARY KEY (IDEDI));

/* Table: TIZOX, Owner: SYSDBA */
CREATE TABLE TIZOX (ID INTEGER NOT NULL,
        NAIM VARCHAR(30) NOT NULL,
CONSTRAINT PK_TIZOX PRIMARY KEY (ID));

/* Table: TKABINS, Owner: SYSDBA */
CREATE TABLE TKABINS (IDKABIN INTEGER NOT NULL,
        BUYURT VARCHAR(30) NOT NULL,
        TEL VARCHAR(30) NOT NULL,
        FORTIME VARCHAR(30) NOT NULL,
        ZAKAZ VARCHAR(30) NOT NULL,
        ZAKOLAT INTEGER DEFAULT 0 NOT NULL,
        ISREZERV INTEGER DEFAULT 0 NOT NULL,
        MESTIMOST INTEGER DEFAULT 0 NOT NULL,
        GOST INTEGER DEFAULT 0 NOT NULL);

/* Table: TMOVES, Owner: SYSDBA */
CREATE TABLE TMOVES (ALLORDERID INTEGER NOT NULL,
        BLUDID INTEGER NOT NULL,
        KOLVO INTEGER DEFAULT 1 NOT NULL,
        PRICE INTEGER DEFAULT 1 NOT NULL,
        SDATE TIMESTAMP DEFAULT current_timestamp
 NOT NULL,
        SUSERID INTEGER DEFAULT 1 NOT NULL,
        IZOX VARCHAR(30) DEFAULT '',
        COMENT VARCHAR(15) DEFAULT '' NOT NULL);

/* Table: TMOVESARCH, Owner: SYSDBA */
CREATE TABLE TMOVESARCH (ALLORDERID INTEGER NOT NULL,
        BLUDID INTEGER NOT NULL,
        KOLVO INTEGER NOT NULL,
        PRICE INTEGER NOT NULL,
        SDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
 NOT NULL,
        SUSERID INTEGER DEFAULT 1 NOT NULL,
        IZOX VARCHAR(30));

/* Table: TNAKLS, Owner: SYSDBA */
CREATE TABLE TNAKLS (IDNAKL INTEGER NOT NULL,
        NDATE TIMESTAMP DEFAULT current_timestamp
 NOT NULL,
        IDCLI INTEGER,
        NTIP INTEGER,
        IZOH VARCHAR(30),
CONSTRAINT PK_TNAKLS PRIMARY KEY (IDNAKL));

/* Table: TORDERS, Owner: SYSDBA */
CREATE TABLE TORDERS (ALLORDERID INTEGER NOT NULL,
        ORDERID INTEGER NOT NULL,
        USERID INTEGER NOT NULL,
        STOL INTEGER DEFAULT 1 NOT NULL,
        OPENED TIMESTAMP NOT NULL,
        CLOSED TIMESTAMP NOT NULL,
        PLASTIK INTEGER DEFAULT 0 NOT NULL,
        WSUMM INTEGER DEFAULT 0 NOT NULL,
        KABINASUMM INTEGER DEFAULT 0 NOT NULL,
        "RESERV" INTEGER DEFAULT 0 NOT NULL,
        DANGER INTEGER DEFAULT 0 NOT NULL,
        COLOR INTEGER DEFAULT 0 NOT NULL,
        IZOX VARCHAR(30) DEFAULT '',
        SKIDKA INTEGER DEFAULT 0 NOT NULL,
        BAND INTEGER DEFAULT 0 NOT NULL,
CONSTRAINT PK_TORDERS PRIMARY KEY (ALLORDERID));

/* Table: TORDERSARCH, Owner: SYSDBA */
CREATE TABLE TORDERSARCH (ALLORDERID INTEGER NOT NULL,
        ORDERID INTEGER NOT NULL,
        USERID INTEGER NOT NULL,
        STOL INTEGER NOT NULL,
        OPENED TIMESTAMP NOT NULL,
        CLOSED TIMESTAMP NOT NULL,
        PLASTIK INTEGER NOT NULL,
        WSUMM INTEGER NOT NULL,
        KABINASUMM INTEGER NOT NULL,
        "RESERV" INTEGER NOT NULL,
        DANGER INTEGER DEFAULT 0 NOT NULL,
        IZOX VARCHAR(30) DEFAULT '',
        SKIDKA INTEGER DEFAULT 0 NOT NULL,
CONSTRAINT PK_TORDERSARCH PRIMARY KEY (ALLORDERID));

/* Table: TOTDELS, Owner: SYSDBA */
CREATE TABLE TOTDELS (OTDELID INTEGER NOT NULL,
        NAIM VARCHAR(50) DEFAULT 'New otdel' NOT NULL,
        PRR INTEGER DEFAULT 0 NOT NULL,
        PRR2 INTEGER DEFAULT 0 NOT NULL,
        PRR3 INTEGER DEFAULT 0 NOT NULL,
        TIPPRR INTEGER DEFAULT 0 NOT NULL,
CONSTRAINT PK_TOTDELS PRIMARY KEY (OTDELID));

/* Table: TSTOLS, Owner: SYSDBA */
CREATE TABLE TSTOLS (STOLID INTEGER NOT NULL,
        SUMM INTEGER DEFAULT 0 NOT NULL,
        "RESERV" INTEGER DEFAULT 0 NOT NULL,
CONSTRAINT PK_TSTOLS PRIMARY KEY (STOLID));

/* Table: TTK, Owner: SYSDBA */
CREATE TABLE TTK (IDBLUD INTEGER NOT NULL,
        TIPTB SMALLINT DEFAULT 0 NOT NULL,
        IDTB INTEGER DEFAULT 1 NOT NULL,
        KOLVO DOUBLE PRECISION DEFAULT 1 NOT NULL);

/* Table: TTMOVES, Owner: SYSDBA */
CREATE TABLE TTMOVES (IDTMOV INTEGER NOT NULL,
        IDNAKL INTEGER NOT NULL,
        IDTOVAR INTEGER NOT NULL,
        KOLVO DOUBLE PRECISION,
        PRICE DOUBLE PRECISION,
CONSTRAINT PK_TTMOVES PRIMARY KEY (IDTMOV));

/* Table: TTMPPRN, Owner: SYSDBA */
CREATE TABLE TTMPPRN (IDTMP INTEGER NOT NULL,
        IDOTDEL INTEGER DEFAULT 1 NOT NULL,
        DTA VARCHAR(1000) NOT NULL,
CONSTRAINT PK_TTMPPRN PRIMARY KEY (IDTMP));

/* Table: TTOVARS, Owner: SYSDBA */
CREATE TABLE TTOVARS (IDTOVAR INTEGER NOT NULL,
        NAIM VARCHAR(30),
        IDEDI INTEGER DEFAULT 1 NOT NULL,
        KOD VARCHAR(10) DEFAULT '000' NOT NULL,
        TIPTOV INTEGER DEFAULT 0 NOT NULL,
        REVIZ FLOAT DEFAULT 0 NOT NULL,
        AVGPRICE FLOAT DEFAULT 0 NOT NULL,
CONSTRAINT PK_TTOVARS PRIMARY KEY (IDTOVAR));

/* Table: TUSERS, Owner: SYSDBA */
CREATE TABLE TUSERS (USERID INTEGER NOT NULL,
        USERNAIM VARCHAR(50) DEFAULT 'New' NOT NULL,
        ROLE SMALLINT DEFAULT 1 NOT NULL,
        PASSW VARCHAR(10) DEFAULT '123456' NOT NULL,
        WORKERID INTEGER DEFAULT 1 NOT NULL,
        ISACTIVE SMALLINT DEFAULT 1 NOT NULL,
        FOIZ INTEGER DEFAULT 0 NOT NULL,
        OPENSTOL INTEGER DEFAULT 1 NOT NULL,
        CLOSESTOL INTEGER DEFAULT 1 NOT NULL,
        PRINT INTEGER DEFAULT 1 NOT NULL,
        CHANGESTOL INTEGER DEFAULT 1 NOT NULL,
        OTKAZ INTEGER DEFAULT 1 NOT NULL,
CONSTRAINT PK_TUSERS PRIMARY KEY (USERID));

/*  Index definitions for all user tables */
CREATE INDEX TMOVESARCH_IDX1 ON TMOVESARCH (ALLORDERID);

ALTER TABLE TBLUDS ADD CONSTRAINT FK_TBLUDS_1 FOREIGN KEY (OTDELID) REFERENCES TOTDELS (OTDELID);

ALTER TABLE TMOVES ADD CONSTRAINT FK_TMOVES_1 FOREIGN KEY (BLUDID) REFERENCES TBLUDS (BLUDID);

ALTER TABLE TMOVESARCH ADD CONSTRAINT FK_TMOVESARCH_1 FOREIGN KEY (BLUDID) REFERENCES TBLUDS (BLUDID);

ALTER TABLE TNAKLS ADD CONSTRAINT FK_TNAKLS_1 FOREIGN KEY (IDCLI) REFERENCES TOTDELS (OTDELID);

ALTER TABLE TORDERS ADD CONSTRAINT FK_TORDERS_1 FOREIGN KEY (USERID) REFERENCES TUSERS (USERID);

ALTER TABLE TORDERSARCH ADD CONSTRAINT FK_TORDERSARCH_1 FOREIGN KEY (USERID) REFERENCES TUSERS (USERID);

ALTER TABLE TTK ADD CONSTRAINT FK_TTK_1 FOREIGN KEY (IDBLUD) REFERENCES TBLUDS (BLUDID);

ALTER TABLE TTMOVES ADD CONSTRAINT FK_TTMOVES_1 FOREIGN KEY (IDNAKL) REFERENCES TNAKLS (IDNAKL);

ALTER TABLE TTMOVES ADD CONSTRAINT FK_TTMOVES_2 FOREIGN KEY (IDTOVAR) REFERENCES TTOVARS (IDTOVAR);

ALTER TABLE TTOVARS ADD CONSTRAINT FK_TTOVARS_1 FOREIGN KEY (IDEDI) REFERENCES TEDIZM (IDEDI);
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures */
CREATE PROCEDURE GETBLUDPRICE (IDBLUD INTEGER)
RETURNS (BLUDPRICE INTEGER)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE GETOSTATKA (IDBLUD INTEGER NOT NULL,
IDTOVAR INTEGER NOT NULL)
RETURNS (OSTATKA FLOAT)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE GETTOVPRICE (IDTOV INTEGER)
RETURNS (TOVPRICE DOUBLE PRECISION)
AS 
BEGIN SUSPEND; END ^

ALTER PROCEDURE GETBLUDPRICE (IDBLUD INTEGER)
RETURNS (BLUDPRICE INTEGER)
AS 
declare variable KOLVO double precision;
declare variable IDTB integer;
declare variable CPRICE double precision;
declare variable TIPTB integer;
declare variable SUMTOV double precision;
declare variable VIHOD double precision;
begin
  /* Б.Р.Р. */
  sumtov=0;
  for
    select idtb, kolvo,tiptb from ttk
    where idblud=:idblud
    into :idtb, :kolvo, :tiptb
  do begin
    if (tiptb=0)
    then
        execute procedure gettovprice(idtb) returning_values cprice;
    else 
        if (idtb<>:idblud)
        then execute procedure getbludprice(idtb) returning_values cprice;
        else cprice=0;
    sumtov=sumtov+kolvo*cprice;
  end
  vihod=1;
  select vihod from tbluds where bludid=:idblud
  into :vihod;
  bludprice=sumtov/vihod;
  suspend;
end
 ^

ALTER PROCEDURE GETOSTATKA (IDBLUD INTEGER NOT NULL,
IDTOVAR INTEGER NOT NULL)
RETURNS (OSTATKA FLOAT)
AS 
declare variable REV float;
declare variable PRIHOD float;
declare variable SOTUV float;
declare variable SOTUVNEW float;
begin
  /* Б.Р.Р. */
  REV=0;
  select REVIZ from TTOVARS where idtovar=:idtovar INTO :rev;

  PRIHOD=0;
  select coalesce(sum(kolvo),0) from ttmoves where idtovar=:idtovar into :prihod;
  SOTUV=0;
  select coalesce(sum(kolvo),0) from tmovesarch where BLUDID=:IDBLUD INTO :sotuv;
  SOTUVNEW=0;
  select coalesce(sum(kolvo),0) from tmoves where BLUDID=:IDBLUD INTO :sotuvnew;
  --if (sotuvnew=null) then sotuvnew=0;

  OSTATKA=REV+PRIHOD-SOTUV-sotuvnew;

  suspend;
end ^

ALTER PROCEDURE GETTOVPRICE (IDTOV INTEGER)
RETURNS (TOVPRICE DOUBLE PRECISION)
AS 
begin
  /* Б.Р.Р. */
   SELECT AVGPRICE FROM TTOVARS WHERE IDTOVAR=:idtov
  /*tovprice=0;
  SELECT m.PRICE*e.koeff FROM TTMOVES m JOIN TNAKLS n on m.IDNAKL=n.IDNAKL AND n.NTIP=0
  JOIN ttovars t on t.idtovar=m.idtovar JOIN TEDIZM e on e.idedi=t.idedi
  WHERE m.IDTOVAR=:idtov ORDER BY n.NDATE DESC ROWS 1*/
  INTO :tovprice;
  suspend;
end ^
SET TERM ; ^
COMMIT WORK ;
SET AUTODDL ON;
